// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: forwarder/v1/forwarder.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForwarderConfigService_GetConfig_FullMethodName     = "/nais.tunnel.forwarder.v1.ForwarderConfigService/GetConfig"
	ForwarderConfigService_StreamUpdates_FullMethodName = "/nais.tunnel.forwarder.v1.ForwarderConfigService/StreamUpdates"
)

// ForwarderConfigServiceClient is the client API for ForwarderConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForwarderConfigServiceClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ForwarderConfig, error)
	StreamUpdates(ctx context.Context, in *StreamUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TunnelUpdate], error)
}

type forwarderConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwarderConfigServiceClient(cc grpc.ClientConnInterface) ForwarderConfigServiceClient {
	return &forwarderConfigServiceClient{cc}
}

func (c *forwarderConfigServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ForwarderConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwarderConfig)
	err := c.cc.Invoke(ctx, ForwarderConfigService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwarderConfigServiceClient) StreamUpdates(ctx context.Context, in *StreamUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TunnelUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ForwarderConfigService_ServiceDesc.Streams[0], ForwarderConfigService_StreamUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamUpdatesRequest, TunnelUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForwarderConfigService_StreamUpdatesClient = grpc.ServerStreamingClient[TunnelUpdate]

// ForwarderConfigServiceServer is the server API for ForwarderConfigService service.
// All implementations must embed UnimplementedForwarderConfigServiceServer
// for forward compatibility.
type ForwarderConfigServiceServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*ForwarderConfig, error)
	StreamUpdates(*StreamUpdatesRequest, grpc.ServerStreamingServer[TunnelUpdate]) error
	mustEmbedUnimplementedForwarderConfigServiceServer()
}

// UnimplementedForwarderConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwarderConfigServiceServer struct{}

func (UnimplementedForwarderConfigServiceServer) GetConfig(context.Context, *GetConfigRequest) (*ForwarderConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedForwarderConfigServiceServer) StreamUpdates(*StreamUpdatesRequest, grpc.ServerStreamingServer[TunnelUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUpdates not implemented")
}
func (UnimplementedForwarderConfigServiceServer) mustEmbedUnimplementedForwarderConfigServiceServer() {
}
func (UnimplementedForwarderConfigServiceServer) testEmbeddedByValue() {}

// UnsafeForwarderConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwarderConfigServiceServer will
// result in compilation errors.
type UnsafeForwarderConfigServiceServer interface {
	mustEmbedUnimplementedForwarderConfigServiceServer()
}

func RegisterForwarderConfigServiceServer(s grpc.ServiceRegistrar, srv ForwarderConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedForwarderConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwarderConfigService_ServiceDesc, srv)
}

func _ForwarderConfigService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwarderConfigServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwarderConfigService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwarderConfigServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwarderConfigService_StreamUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ForwarderConfigServiceServer).StreamUpdates(m, &grpc.GenericServerStream[StreamUpdatesRequest, TunnelUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForwarderConfigService_StreamUpdatesServer = grpc.ServerStreamingServer[TunnelUpdate]

// ForwarderConfigService_ServiceDesc is the grpc.ServiceDesc for ForwarderConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwarderConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nais.tunnel.forwarder.v1.ForwarderConfigService",
	HandlerType: (*ForwarderConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _ForwarderConfigService_GetConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpdates",
			Handler:       _ForwarderConfigService_StreamUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "forwarder/v1/forwarder.proto",
}
