// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forwarder/v1/forwarder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateType int32

const (
	UpdateType_ADDED    UpdateType = 0
	UpdateType_MODIFIED UpdateType = 1
	UpdateType_DELETED  UpdateType = 2
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "ADDED",
		1: "MODIFIED",
		2: "DELETED",
	}
	UpdateType_value = map[string]int32{
		"ADDED":    0,
		"MODIFIED": 1,
		"DELETED":  2,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_forwarder_v1_forwarder_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_forwarder_v1_forwarder_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_forwarder_v1_forwarder_proto_rawDescGZIP(), []int{0}
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_forwarder_v1_forwarder_proto_rawDescGZIP(), []int{0}
}

type StreamUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamUpdatesRequest) Reset() {
	*x = StreamUpdatesRequest{}
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUpdatesRequest) ProtoMessage() {}

func (x *StreamUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_forwarder_v1_forwarder_proto_rawDescGZIP(), []int{1}
}

type ForwarderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LbVip         *string                `protobuf:"bytes,1,opt,name=lb_vip,json=lbVip" json:"lb_vip,omitempty"`
	Tunnels       []*TunnelMapping       `protobuf:"bytes,2,rep,name=tunnels" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwarderConfig) Reset() {
	*x = ForwarderConfig{}
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwarderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwarderConfig) ProtoMessage() {}

func (x *ForwarderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwarderConfig.ProtoReflect.Descriptor instead.
func (*ForwarderConfig) Descriptor() ([]byte, []int) {
	return file_forwarder_v1_forwarder_proto_rawDescGZIP(), []int{2}
}

func (x *ForwarderConfig) GetLbVip() string {
	if x != nil && x.LbVip != nil {
		return *x.LbVip
	}
	return ""
}

func (x *ForwarderConfig) GetTunnels() []*TunnelMapping {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type TunnelMapping struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TunnelName      *string                `protobuf:"bytes,1,opt,name=tunnel_name,json=tunnelName" json:"tunnel_name,omitempty"`
	TunnelNamespace *string                `protobuf:"bytes,2,opt,name=tunnel_namespace,json=tunnelNamespace" json:"tunnel_namespace,omitempty"`
	ForwarderPort   *int32                 `protobuf:"varint,3,opt,name=forwarder_port,json=forwarderPort" json:"forwarder_port,omitempty"`
	GatewayAddress  *string                `protobuf:"bytes,4,opt,name=gateway_address,json=gatewayAddress" json:"gateway_address,omitempty"` // pod IP:port e.g. "10.0.0.5:51820"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TunnelMapping) Reset() {
	*x = TunnelMapping{}
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMapping) ProtoMessage() {}

func (x *TunnelMapping) ProtoReflect() protoreflect.Message {
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMapping.ProtoReflect.Descriptor instead.
func (*TunnelMapping) Descriptor() ([]byte, []int) {
	return file_forwarder_v1_forwarder_proto_rawDescGZIP(), []int{3}
}

func (x *TunnelMapping) GetTunnelName() string {
	if x != nil && x.TunnelName != nil {
		return *x.TunnelName
	}
	return ""
}

func (x *TunnelMapping) GetTunnelNamespace() string {
	if x != nil && x.TunnelNamespace != nil {
		return *x.TunnelNamespace
	}
	return ""
}

func (x *TunnelMapping) GetForwarderPort() int32 {
	if x != nil && x.ForwarderPort != nil {
		return *x.ForwarderPort
	}
	return 0
}

func (x *TunnelMapping) GetGatewayAddress() string {
	if x != nil && x.GatewayAddress != nil {
		return *x.GatewayAddress
	}
	return ""
}

type TunnelUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *UpdateType            `protobuf:"varint,1,opt,name=type,enum=nais.tunnel.forwarder.v1.UpdateType" json:"type,omitempty"`
	Tunnel        *TunnelMapping         `protobuf:"bytes,2,opt,name=tunnel" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelUpdate) Reset() {
	*x = TunnelUpdate{}
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelUpdate) ProtoMessage() {}

func (x *TunnelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_forwarder_v1_forwarder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelUpdate.ProtoReflect.Descriptor instead.
func (*TunnelUpdate) Descriptor() ([]byte, []int) {
	return file_forwarder_v1_forwarder_proto_rawDescGZIP(), []int{4}
}

func (x *TunnelUpdate) GetType() UpdateType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return UpdateType_ADDED
}

func (x *TunnelUpdate) GetTunnel() *TunnelMapping {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

var File_forwarder_v1_forwarder_proto protoreflect.FileDescriptor

const file_forwarder_v1_forwarder_proto_rawDesc = "" +
	"\n" +
	"\x1cforwarder/v1/forwarder.proto\x12\x18nais.tunnel.forwarder.v1\"\x12\n" +
	"\x10GetConfigRequest\"\x16\n" +
	"\x14StreamUpdatesRequest\"k\n" +
	"\x0fForwarderConfig\x12\x15\n" +
	"\x06lb_vip\x18\x01 \x01(\tR\x05lbVip\x12A\n" +
	"\atunnels\x18\x02 \x03(\v2'.nais.tunnel.forwarder.v1.TunnelMappingR\atunnels\"\xab\x01\n" +
	"\rTunnelMapping\x12\x1f\n" +
	"\vtunnel_name\x18\x01 \x01(\tR\n" +
	"tunnelName\x12)\n" +
	"\x10tunnel_namespace\x18\x02 \x01(\tR\x0ftunnelNamespace\x12%\n" +
	"\x0eforwarder_port\x18\x03 \x01(\x05R\rforwarderPort\x12'\n" +
	"\x0fgateway_address\x18\x04 \x01(\tR\x0egatewayAddress\"\x89\x01\n" +
	"\fTunnelUpdate\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.nais.tunnel.forwarder.v1.UpdateTypeR\x04type\x12?\n" +
	"\x06tunnel\x18\x02 \x01(\v2'.nais.tunnel.forwarder.v1.TunnelMappingR\x06tunnel*2\n" +
	"\n" +
	"UpdateType\x12\t\n" +
	"\x05ADDED\x10\x00\x12\f\n" +
	"\bMODIFIED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x022\xeb\x01\n" +
	"\x16ForwarderConfigService\x12d\n" +
	"\tGetConfig\x12*.nais.tunnel.forwarder.v1.GetConfigRequest\x1a).nais.tunnel.forwarder.v1.ForwarderConfig\"\x00\x12k\n" +
	"\rStreamUpdates\x12..nais.tunnel.forwarder.v1.StreamUpdatesRequest\x1a&.nais.tunnel.forwarder.v1.TunnelUpdate\"\x000\x01B5Z3github.com/nais/tunnel-operator/pkg/forwarder/protob\beditionsp\xe8\a"

var (
	file_forwarder_v1_forwarder_proto_rawDescOnce sync.Once
	file_forwarder_v1_forwarder_proto_rawDescData []byte
)

func file_forwarder_v1_forwarder_proto_rawDescGZIP() []byte {
	file_forwarder_v1_forwarder_proto_rawDescOnce.Do(func() {
		file_forwarder_v1_forwarder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forwarder_v1_forwarder_proto_rawDesc), len(file_forwarder_v1_forwarder_proto_rawDesc)))
	})
	return file_forwarder_v1_forwarder_proto_rawDescData
}

var file_forwarder_v1_forwarder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_forwarder_v1_forwarder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_forwarder_v1_forwarder_proto_goTypes = []any{
	(UpdateType)(0),              // 0: nais.tunnel.forwarder.v1.UpdateType
	(*GetConfigRequest)(nil),     // 1: nais.tunnel.forwarder.v1.GetConfigRequest
	(*StreamUpdatesRequest)(nil), // 2: nais.tunnel.forwarder.v1.StreamUpdatesRequest
	(*ForwarderConfig)(nil),      // 3: nais.tunnel.forwarder.v1.ForwarderConfig
	(*TunnelMapping)(nil),        // 4: nais.tunnel.forwarder.v1.TunnelMapping
	(*TunnelUpdate)(nil),         // 5: nais.tunnel.forwarder.v1.TunnelUpdate
}
var file_forwarder_v1_forwarder_proto_depIdxs = []int32{
	4, // 0: nais.tunnel.forwarder.v1.ForwarderConfig.tunnels:type_name -> nais.tunnel.forwarder.v1.TunnelMapping
	0, // 1: nais.tunnel.forwarder.v1.TunnelUpdate.type:type_name -> nais.tunnel.forwarder.v1.UpdateType
	4, // 2: nais.tunnel.forwarder.v1.TunnelUpdate.tunnel:type_name -> nais.tunnel.forwarder.v1.TunnelMapping
	1, // 3: nais.tunnel.forwarder.v1.ForwarderConfigService.GetConfig:input_type -> nais.tunnel.forwarder.v1.GetConfigRequest
	2, // 4: nais.tunnel.forwarder.v1.ForwarderConfigService.StreamUpdates:input_type -> nais.tunnel.forwarder.v1.StreamUpdatesRequest
	3, // 5: nais.tunnel.forwarder.v1.ForwarderConfigService.GetConfig:output_type -> nais.tunnel.forwarder.v1.ForwarderConfig
	5, // 6: nais.tunnel.forwarder.v1.ForwarderConfigService.StreamUpdates:output_type -> nais.tunnel.forwarder.v1.TunnelUpdate
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_forwarder_v1_forwarder_proto_init() }
func file_forwarder_v1_forwarder_proto_init() {
	if File_forwarder_v1_forwarder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forwarder_v1_forwarder_proto_rawDesc), len(file_forwarder_v1_forwarder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forwarder_v1_forwarder_proto_goTypes,
		DependencyIndexes: file_forwarder_v1_forwarder_proto_depIdxs,
		EnumInfos:         file_forwarder_v1_forwarder_proto_enumTypes,
		MessageInfos:      file_forwarder_v1_forwarder_proto_msgTypes,
	}.Build()
	File_forwarder_v1_forwarder_proto = out.File
	file_forwarder_v1_forwarder_proto_goTypes = nil
	file_forwarder_v1_forwarder_proto_depIdxs = nil
}
