replicaCount: 1

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/tunnel-operator
  pullPolicy: IfNotPresent
  tag: ""

gatewayImage: europe-north1-docker.pkg.dev/nais-io/nais/images/tunnel-operator-gateway:latest

serviceAccount:
  create: true
  name: tunnel-operator
  email: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

tenant:
  domain: example.com

clusters: ""

staticClusters: ""

fasit:
  tenant:
    name: ""
