replicaCount: 1

logLevel: "debug"

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/tunnel-operator
  pullPolicy: IfNotPresent
  tag: ""

grpc:
  port: 9090

forwarderPortRange:
  min: 51820
  max: 51919

apiServer:
  address: ""

gatewayImage: europe-north1-docker.pkg.dev/nais-io/nais/images/tunnel-operator-gateway:latest

serviceAccount:
  create: true
  name: tunnel-operator
  email: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

forwarder:
  enabled: true
  image:
    repository: europe-north1-docker.pkg.dev/nais-io/nais/images/tunnel-operator-forwarder
    pullPolicy: IfNotPresent
    tag: ""
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
  portRange:
    min: 51820
    max: 51919
  grpcAddr: "tunnel-operator:9090"
  healthAddr: ":8080"
  logLevel: "debug"
