{{- if .Values.forwarder.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tunnel-operator.fullname" . }}-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnel-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: forwarder
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    {{- include "tunnel-operator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: forwarder
  ports:
    {{- range untilStep (int .Values.forwarder.portRange.min) (add1 (int .Values.forwarder.portRange.max) | int) 1 }}
    - name: wg-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
    {{- end }}
{{- end }}
