{{- if .Values.forwarder.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tunnel-operator.fullname" . }}-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnel-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: forwarder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tunnel-operator.fullname" . }}-forwarder
  minReplicas: {{ .Values.forwarder.hpa.minReplicas }}
  maxReplicas: {{ .Values.forwarder.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.forwarder.hpa.targetCPUUtilizationPercentage }}
{{- end }}
