{{- if .Values.forwarder.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "tunnel-operator.fullname" . }}-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnel-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: forwarder
spec:
  podMetricsEndpoints:
    - interval: 1m
      port: health
      path: /metrics
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "tunnel-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: forwarder
{{- end }}
