apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tunnel-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnel-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tunnel-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "tunnel-operator.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: forwarder
      ports:
        - protocol: TCP
          port: {{ .Values.grpc.port }}
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.apiServer.address }}
    - to:
        - ipBlock:
            cidr: {{ .Values.apiServer.address }}
      ports:
        - protocol: TCP
          port: 443
    {{- end }}
