apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "tunnel-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnel-operator.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - interval: 1m
      port: metrics
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "tunnel-operator.selectorLabels" . | nindent 6 }}
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: DoesNotExist
