apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tunnel-operator.fullname" . }}
  labels:
    {{- include "tunnel-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["nais.io"]
    resources: ["tunnels"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["nais.io"]
    resources: ["tunnels/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["nais.io"]
    resources: ["tunnels/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
