apiVersion: v1
kind: Service
metadata:
  name: {{ include "tunnel-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tunnel-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: {{ .Values.grpc.port }}
    targetPort: grpc
    protocol: TCP
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  selector:
    {{- include "tunnel-operator.selectorLabels" . | nindent 4 }}
