apiVersion: nais.io/v1alpha1
kind: Tunnel
metadata:
  labels:
    app.kubernetes.io/name: tunnel
    app.kubernetes.io/instance: tunnel-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: tunnel-sample
spec:
  teamSlug: sample-team
  environment: dev
  clientPublicKey: sample-public-key
  target:
    host: redis.example.com
    port: 6379
    resolvedIP: 10.0.0.10
