environmentKinds:
  - tenant

values:
  serviceAccountEmail:
    displayName: Operator GCP SA email
    description: GCP service account email of the tunnel-operator (for RBAC binding)
    computed:
      template: |
        {{ .Management.tunnel_operator_name | quote }}
