apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tunnel-operator
  labels:
    app.kubernetes.io/name: tunnel-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: ["nais.io"]
  resources: ["tunnels"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["nais.io"]
  resources: ["tunnels/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["nais.io"]
  resources: ["tunnels/finalizers"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tunnel-operator
  labels:
    app.kubernetes.io/name: tunnel-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tunnel-operator
subjects:
- kind: User
  name: {{ .Values.serviceAccountEmail | quote }}
  apiGroup: rbac.authorization.k8s.io
